name: LatePenalty

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10.9
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - jupyterlab
  - partd
  - bokeh
  - nbdev
  - gh
  - pip
  - pip:
    - PyGithub
    - canvasapi
